Fix Mistakes

diff --git a/usr/lib/wich/wich b/usr/lib/wich/wich
--- a/usr/lib/wich/wich
+++ b/usr/lib/wich/wich
@@ -9,7 +9,7 @@
 #  net-tools: You probably have them installed
 
 
-function usage(){
+usage(){
 	echo "Wich script by Roach"
 	echo "	Usage wich [OPTIONS] {PERAMETERS}"
 	echo "		-1 or --man :	Put Given Interface Into Managed Mode"
@@ -19,10 +19,12 @@ function usage(){
 	echo "		-5 or --creds : To Capture Credentials On LAN ('wich --creds --help' For More Info)"
 	echo "		-6 or --wifijam : To Jam All Wifi Signals In Range ('wich --wifijam --help' For More Info)"
 	echo "		-7 or --cread :	Recontruct Information and Images From Pcap Dump ('wich --cread --help' For More Info)"
+	echo "		-8 or --rand : Randomize MAC Address"
 	echo "		-h or --help :	To Show This Help Test"
 	echo "	Examples :"
 	echo "		To put into managed mode ...wich -1 'interface name'"
 	echo "		To put into monitor mode ...wich -2 'interface name'"
+	echo "		To randomize MAC Address ...wich -8 'interface name'"
 	echo "		To put into master mode ...wich -3 'interface name' 'interface name' 'essid' 'password'"
 	echo "		To stop hosted AP ...wich -4 'hosted interface name'"
 	echo "		To capture credentials ...wich -5 -i 'interface name'"
@@ -30,55 +32,80 @@ function usage(){
 	echo "		To extract info/images from pcap ...wich -7 'pcap dump'"
 }
 
-function manm(){
+manm(){
 	sudo /sbin/ifconfig $1 down;
-	sudo /usr/lib/wich/macspoof -r $1;
-	sudo /sbin/iwconfig $1 mode managed;
-	sudo /sbin/ifconfig $1 up;
-	sudo service network-manager restart;
-	tput bold;
-	echo "Managed mode enabled on $1"
+	sudo /usr/lib/wich/macspoof -A $1;
+	if (( $? != 0 )); then
+		tput bold;
+		echo "[Error]: Device busy or not present!";
+		exit 125;
+	else
+		sudo /sbin/iwconfig $1 mode managed;
+		sudo /sbin/ifconfig $1 up;
+		sudo service network-manager restart;
+		tput bold;
+		echo "Managed mode enabled on $1"
+	fi
 }
 
-function monm(){
+monm(){
 	sudo /sbin/ifconfig $1 down;
-	sudo /usr/lib/wich/macspoof -r $1;
-	sudo /sbin/iwconfig $1 mode monitor:
-	sudo /sbin/ifconfig $1 up;
-	sudo service network-manager stop
-	tput bold;
-	echo "Monitor mode enabled on $1"
+	sudo /usr/lib/wich/macspoof -A $1;
+	if (( $? != 0 )); then
+		tput bold;
+		echo "[Error]: Device busy or not present!";
+		exit 125;
+	else
+		sudo /sbin/iwconfig $1 mode monitor:
+		sudo /sbin/ifconfig $1 up;
+		sudo service network-manager stop
+		tput bold;
+		echo "Monitor mode enabled on $1"
+	fi
 }
 
-function mas(){
+rand(){
+	sudo /sbin/ifconfig $1 down;
+	sudo /usr/lib/wich/macspoof -r $1;
+	if (( $? != 0 )); then
+		tput bold;
+		echo "[Error]: Device busy or not present!";
+		exit 125;
+	else
+		sudo /sbin/ifconfig $1 up;
+	fi
+}
+
+mas(){
 	sudo /usr/lib/wich/hostap --daemon $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25}
 }
 
-function masstop(){
+masstop(){
 	sudo /usr/lib/wich/hostap --stop $1
 }
 
-function creds(){
+creds(){
 	sudo /usr/lib/wich/creds $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25}
 }
 
-function wifijam(){
+wifijam(){
 	sudo /usr/lib/wich/wifijam $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25}
 }
 
-function cread(){
+cread(){
 	sudo /usr/lib/wich/cread $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25}
 }
 
 case $1 in
 	-h|--help) usage; exit 0;;
-	-1|--man) manm $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25}; exit 0;;
-	-2|--mon) monm $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25}; exit 0;;
+	-1|--man) manm $2; exit 0;;
+	-2|--mon) monm $2; exit 0;;
 	-3|--host) mas $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25}; exit 0;;
-	-4|--stop) masstop $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25}; exit 0;;
+	-4|--stop) masstop $2; exit 0;;
 	-5|--creds) creds $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25}; exit 0;;
 	-6|--wifijam) wifijam $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25}; exit 0;;
-	-7|--cread) cread $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25};exit 0;;
+	-7|--cread) cread $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25}; exit 0;;
+	-8|--rand) rand $2; exit 0;;
 	*) echo "Uknown command '$1' type 'wich --help' for help!"; exit 125;;
 esac
 
