...

diff --git a/usr/lib/wich/wich b/usr/lib/wich/wich
--- a/usr/lib/wich/wich
+++ b/usr/lib/wich/wich
@@ -33,55 +33,46 @@ usage(){
 }
 
 manm(){
-	if (( -z $1 )); then echo "Please enter wireless interface!"; exit 125;
+	sudo /sbin/ifconfig $1 down;
+	sudo /usr/lib/wich/macspoof -A $1 2> /dev/null;
+	if (( $? != 0 )); then
+		tput bold;
+		echo "[Error]: Device busy or not present!";
+		exit 125;
 	else
-		sudo /sbin/ifconfig $1 down;
-		sudo /usr/lib/wich/macspoof -A $1 2> /dev/null;
-		if (( $? != 0 )); then
-			tput bold;
-			echo "[Error]: Device busy or not present!";
-			exit 125;
-		else
-			sudo /sbin/iwconfig $1 mode managed;
-			sudo /sbin/ifconfig $1 up;
-			sudo service network-manager restart;
-			tput bold;
-			echo "Managed mode enabled on $1"
-		fi
+		sudo /sbin/iwconfig $1 mode managed;
+		sudo /sbin/ifconfig $1 up;
+		sudo service network-manager restart;
+		tput bold;
+		echo "Managed mode enabled on $1"
 	fi
 }
 
 monm(){
-	if (( -z $1 )); then echo "Please enter wireless interface!"; exit 125;
+	sudo /sbin/ifconfig $1 down;
+	sudo /usr/lib/wich/macspoof -A $1 2> /dev/null;
+	if (( $? != 0 )); then
+		tput bold;
+		echo "[Error]: Device busy or not present!";
+		exit 125;
 	else
-		sudo /sbin/ifconfig $1 down;
-		sudo /usr/lib/wich/macspoof -A $1 2> /dev/null;
-		if (( $? != 0 )); then
-			tput bold;
-			echo "[Error]: Device busy or not present!";
-			exit 125;
-		else
-			sudo /sbin/iwconfig $1 mode monitor:
-			sudo /sbin/ifconfig $1 up;
-			sudo service network-manager stop
-			tput bold;
-			echo "Monitor mode enabled on $1"
-		fi
+		sudo /sbin/iwconfig $1 mode monitor:
+		sudo /sbin/ifconfig $1 up;
+		sudo service network-manager stop
+		tput bold;
+		echo "Monitor mode enabled on $1"
 	fi
 }
 
 rand(){
-	if (( -z $1 )); then echo "Please enter wireless interface!"; exit 125;
+	sudo /sbin/ifconfig $1 down;
+	sudo /usr/lib/wich/macspoof -r $1 2> /dev/null;
+	if (( $? != 0 )); then
+		tput bold;
+		echo "[Error]: Device busy or not present!";
+		exit 125;
 	else
-		sudo /sbin/ifconfig $1 down;
-		sudo /usr/lib/wich/macspoof -r $1 2> /dev/null;
-		if (( $? != 0 )); then
-			tput bold;
-			echo "[Error]: Device busy or not present!";
-			exit 125;
-		else
-			sudo /sbin/ifconfig $1 up;
-		fi
+		sudo /sbin/ifconfig $1 up;
 	fi
 }
 
